### ISSUE TITLE
Shrink image using alpine or slim base

### ISSUE THREAD

**Issue by dhh** [rails/docked#10]
Would be nice if we could shrink the image needed. Maybe we could run this off alpine or slim? Needs some work sorting out the dependencies, though.

**Comment by stillhart** [comment]
Would it be asking too much by providing support to the exact same base images as ruby does? https://hub.docker.com/_/ruby/
That would move it to a "drop-in-replacement".

**Comment by dhh** [comment]
Closed via #11
