### ISSUE TITLE
Bad yarn recommendation in readme

### ISSUE THREAD

**Issue by vovsemenv** [rails/docked#12]
Hello, i guess doing `alias yarn='docked yarn'` as we propose in readme will be very bad for regular developer. 
Maybe we should recommend doing something like `yarn:rails` for this alias?

**Comment by dhh** [comment]
Whole purpose of this setup is to help someone who does not have all the dependencies already installed on their system. If you already have npm, yarn, whatever installed, you're not likely to need this project.
