### ISSUE TITLE
Problem with PG gem

### ISSUE THREAD

**Issue by siba2893** [rails/docked#24]
If trying to create a rails app from scratch using the `--database=postgresql` flag it will run into an error where the `pg` gem wont install because it lacks of a psql installation.

**Comment by durierem** [comment]
See https://github.com/rails/docked/issues/16#issuecomment-1376384582

**Comment by siba2893** [comment]
Got it makes sense.

**Comment by cdwsn** [comment]
For anyone interested in using other databases / javascript options from the beginning in a Dockerized Rails app, I wrote a [bash script](https://github.com/cdwsn/whales) which should do the trick. It uses dockerfile-rails to generate a compose file, which it then copies and edits to provide the dev enviroment.
