### ISSUE TITLE
Ruby versions

### ISSUE THREAD

**Issue by randel-reyes22** [rails/docked#27]
**Is there a way to change the ruby version?**  Because i have a project that uses the old version of ruby.

**Comment by elalemanyo** [comment]
Yes, you need to change it [here](https://github.com/rails/docked/blob/0cb4cb2c72d0079885b50ec0eb6f94651e5a64f9/Dockerfile#L1)

**Comment by durierem** [comment]
You can also provide a value at build time: `docker build --build-arg="RUBY_VERSION=2.6.0" .`

**Comment by elalemanyo** [comment]
yes, the form suggested by @durierem is much better 🙂 I forgot that the ruby version is in an argument.

**Comment by randel-reyes22** [comment]
Ohh great, thank you for the help guys 😁
