### ISSUE TITLE
Use package manager to install Node

### ISSUE THREAD

**Issue by FinnIckler** [rails/docked#29]
The nodesource script way of installing node https://github.com/rails/docked/blob/0cb4cb2c72d0079885b50ec0eb6f94651e5a64f9/Dockerfile#L10 is deprecated and will make you wait for a minute if you are using it. 
The way to do it now is using the deb repository

Like 
```
sudo apt-get update
sudo apt-get install -y ca-certificates curl gnupg
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
sudo apt-get install nodejs -y

```

See https://github.com/nodesource/distributions#debian-and-ubuntu-based-distributions

I could open a PR if needed.

**Comment by jeremy** [comment]
Closed by #30
