### ISSUE TITLE
Incompatibility with Podman (Error: statfs no such file or directory)

### ISSUE THREAD

**Issue by lakuapik** [rails/docked#6]
I follow the instruction in the readme, created a volume, aliased rails.

but when i run `rails new blog` i got this error:

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/20186786/208074398-16f5c2eb-02eb-4e11-a1fe-338f63c66720.png">

PS: i am on mac and use podman as alternative of docker. i dont know if its because of podman or the issue with docker image.

**Comment by dhh** [comment]
I can't replicate this on a fresh macOS install running Docker for Mac. So I'm going to suspect it's a Podman issue. Do let us know if you figure out what the Podman issue is. Or if you don't have the appetite for that, I'd suggest trying Docker for Mac.

**Comment by adrianhj** [comment]
@lakuapik I'm not sure how your Podman set-up looks under OSX, but I would guess you do not have the relevant volumes mounted into its underlying VM for (re-)mounting when executing containers within it.

[podman machine init](https://docs.podman.io/en/latest/markdown/podman-machine-init.1.html) suggests there is a `--volume` option to be passed when initialising the VM to mount volumes from the host; a search for "podman osx mount volume" seems to corroborate it.

**Comment by lakuapik** [comment]
yup it turns out it was the podman problem.

my podman machine was running `rootless` mode, when i stop it then change to `rootful` mode, somehow it works!

```sh
$ podman machine set --rootful podman-machine-default
```
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/20186786/208139213-ab3a3781-736c-43ac-a715-83cb11d2135f.png">

@dhh @adrianhj thank you!
