### ISSUE TITLE
Error when running rails new

### ISSUE THREAD

**Issue by luizpicolo** [rails/docked#9]
I can't generate a new rails app. When running the rails news test command, the image message is always returned.

- MacBook with the latest version of Macos
- I don't have rails installed
- Even running the command `docker run --rm -it -v ${PWD}:/rails -v ruby-bundle-cache:/bundle ghcr.io/rails/cli new test` message is returned

![Captura de Tela 2022-12-17 às 00 03 00](https://user-images.githubusercontent.com/1373275/208224276-713e55f4-d639-4014-b43e-bafdcee40dd7.png)

**Comment by dhh** [comment]
Fixed with latest image 👍
